In [3]:
import json
import requests
import pandas as pd
import matplotlib.pyplot as plt
from pprint import pprint
from config import api_key

In [6]:
url = "https://www.quandl.com/api/v3/datasets/YALE/RBCI.json?"

query_url = f'{url}api_key={api_key}'

CPI = requests.get(query_url).json()

{'dataset': {'collapse': None,
             'column_index': None,
             'column_names': ['Date',
                              'Cost Index',
                              'U.S. Population (Millions)',
                              'Long Rate'],
             'data': [['2018-12-31', None, None, 2.83],
                      ['2017-12-31', None, None, 2.43],
                      ['2016-12-31', None, 323.242, 2.09],
                      ['2015-12-31', 88.5254, 321.704, 1.88],
                      ['2014-12-31', 86.47191, 319.233, 2.86],
                      ['2013-12-31', 86.059965910945, 316.796, 1.91],
                      ['2012-12-31', 85.709697902615, 314.49, 1.97],
                      ['2011-12-31', 86.239087998055, 312.169, 3.39],
                      ['2010-12-31', 84.613931004212, 309.807, 3.73],
                      ['2009-12-31', 84.808354950341, 307.24, 2.52],
                      ['2008-12-31', 83.446159196146, 304.543, 3.74],
                      ['2007-12-31', 83.196606760536, 301.696, 4.76],
                      ['2006-12-31', 82.727011372366, 298.818, 4.42],
                      ['2005-12-31', 82.79484771968, 295.993, 4.22],
                      ['2004-12-31', 80.773025788503, 293.262, 4.15],
                      ['2003-12-31', 76.315435159297, 290.626, 4.05],
                      ['2002-12-31', 76.813539497288, 287.955, 5.04],
                      ['2001-12-31', 76.640160699815, 285.225, 5.16],
                      ['2000-12-31', 78.722001047396, 282.398, 6.66],
                      ['1999-12-31', 78.981281308378, 279.328, 4.72],
                      ['1998-12-31', 78.790605489906, 276.154, 5.54],
                      ['1997-12-31', 79.391464287331, 272.958, 6.58],
                      ['1996-12-31', 77.892859482663, 269.714, 5.65],
                      ['1995-12-31', 77.744309804434, 266.588, 7.78],
                      ['1994-12-31', 79.898871089405, 263.455, 5.75],
                      ['1993-12-31', 78.887880537909, 260.282, 6.6],
                      ['1992-12-31', 77.053819626208, 256.922, 7.03],
                      ['1991-12-31', 76.742074535998, 253.53, 8.09],
                      ['1990-12-31', 79.63498843103, 250.181, 8.21],
                      ['1989-12-31', 81.66945023377, 247.387, 9.09],
                      ['1988-12-31', 84.312854375427, 245.061, 8.67],
                      ['1987-12-31', 85.800117465126, 242.843, 7.08],
                      ['1986-12-31', 85.065639257954, 240.683, 9.19],
                      ['1985-12-31', 86.307251784091, 238.506, 11.38],
                      ['1984-12-31', 89.061595491057, 236.394, 11.67],
                      ['1983-12-31', 91.528301017099, 234.333, 10.46],
                      ['1982-12-31', 88.952770828949, 232.218, 14.59],
                      ['1981-12-31', 90.503876703759, 230.008, 12.57],
                      ['1980-12-31', 93.677209009159, 227.726, 10.8],
                      ['1979-12-31', 100.0, 225.106, 9.1],
                      ['1978-12-31', 100.56884002199, 222.629, 7.96],
                      ['1977-12-31', 99.16550372845, 220.289, 7.21],
                      ['1976-12-31', 96.233897983318, 218.086, 7.74],
                      ['1975-12-31', 94.122500920651, 215.981, 7.5],
                      ['1974-12-31', 97.093271547117, 213.898, 6.99],
                      ['1973-12-31', 100.30455778468, 211.939, 6.46],
                      ['1972-12-31', 95.743095655617, 209.924, 5.95],
                      ['1971-12-31', 89.436185877159, 207.692, 6.24],
                      ['1970-12-31', 83.042895247403, 205.089, 7.79],
                      ['1969-12-31', 83.323038340612, 202.736, 6.04],
                      ['1968-12-31', 79.390564568525, 200.745, 5.53],
                      ['1967-12-31', 77.150510233921, 198.752, 4.58],
                      ['1966-12-31', 76.749267860909, 196.599, 4.61],
                      ['1965-12-31', 75.457246162304, 194.347, 4.19],
                      ['1964-12-31', 74.367117321477, 191.927, 4.17],
                      ['1963-12-31', 73.367017736755, 189.3, 3.83],
                      ['1962-12-31', 72.592999816749, 186.59, 4.08],
                      ['1961-12-31', 71.568196995916, 183.742, 3.84],
                      ['1960-12-31', 71.636142575432, 180.76, 4.72],
                      ['1959-12-31', 70.952967716252, 177.13, 4.02],
                      ['1958-12-31', 68.925714197842, 174.141, 3.09],
                      ['1957-12-31', 69.24632103959, 171.274, 3.46],
                      ['1956-12-31', 68.791487860314, 168.221, 2.9],
                      ['1955-12-31', 65.955282669615, 165.275, 2.61],
                      ['1954-12-31', 62.254476192033, 162.391, 2.48],
                      ['1953-12-31', 60.839220095318, 159.565, 2.83],
                      ['1952-12-31', 58.943437717178, 156.954, 2.68],
                      ['1951-12-31', 59.278698601377, 154.287, 2.57],
                      ['1950-12-31', 59.917186202379, 151.684, 2.32],
                      ['1949-12-31', 55.07055158512, 149.188, 2.31],
                      ['1948-12-31', 54.024908200592, 146.631, 2.44],
                      ['1947-12-31', 54.663052789036, 144.126, 2.25],
                      ['1946-12-31', 54.052764168212, 141.389, 2.19],
                      ['1945-12-31', 50.415711806092, 139.928, 2.37],
                      ['1944-12-31', 50.711518896956, 138.397, 2.48],
                      ['1943-12-31', 50.878790934612, 136.739, 2.47],
                      ['1942-12-31', 53.093496461624, 134.86, 2.46],
                      ['1941-12-31', 56.189005727564, 133.402, 1.95],
                      ['1940-12-31', 54.836438710494, 132.122, 2.21],
                      ['1939-12-31', 52.835545433127, 131.028, 2.36],
                      ['1938-12-31', 52.091382821392, 129.969, 2.56],
                      ['1937-12-31', 52.194526647406, 128.961, 2.68],
                      ['1936-12-31', 46.799085339134, 128.181, 2.65],
                      ['1935-12-31', 45.830773210879, 127.362, 2.79],
                      ['1934-12-31', 47.504039848735, 126.485, 3.12],
                      ['1933-12-31', 43.078444157493, 125.69, 3.31],
                      ['1932-12-31', 34.39721356159, 124.949, 3.68],
                      ['1931-12-31', 39.673467694255, 124.149, 3.34],
                      ['1930-12-31', 40.622217078338, 123.188, 3.29],
                      ['1929-12-31', 41.939694388987, 121.878, 3.6],
                      ['1928-12-31', 40.803719251192, 120.509, 3.33],
                      ['1927-12-31', 39.908269849996, 119.035, 3.34],
                      ['1926-12-31', 38.806698996625, 117.397, 3.68],
                      ['1925-12-31', 39.718513951959, 115.829, 3.86],
                      ['1924-12-31', 40.369637131499, 114.109, 4.06],
                      ['1923-12-31', 41.571114427079, 111.947, 4.36],
                      ['1922-12-31', 34.437609584563, 110.049, 4.3],
                      ['1921-12-31', 32.805185035155, 108.538, 5.09],
                      ['1920-12-31', 40.271799969806, 106.541, 4.97],
                      ['1919-12-31', 36.182717777, 104.514, 4.5],
                      ['1918-12-31', 42.643917380036, 103.208, 4.57],
                      ['1917-12-31', 53.594301367803, 103.268, 4.23],
                      ['1916-12-31', 47.296168647186, 101.961, 4.05],
                      ['1915-12-31', 35.317522956254, 100.546, 4.24],
                      ['1914-12-31', 34.477839354011, 99.111, 4.16],
                      ['1913-12-31', 40.336469535179, 97.225, 4.45],
                      ['1912-12-31', 42.254108323404, 95.335, 4.01],
                      ['1911-12-31', 42.297557688034, 93.863, 3.98],
                      ['1910-12-31', 37.981766718948, 92.407, 3.91],
                      ['1909-12-31', 44.071666122664, 90.49, 3.76],
                      ['1908-12-31', 50.125714115545, 88.71, 3.87],
                      ['1907-12-31', 49.544707383142, 87.008, 3.67],
                      ['1906-12-31', 51.769148434637, 85.45, 3.43],
                      ['1905-12-31', 47.110983749312, 83.822, 3.48],
                      ['1904-12-31', 47.085621062163, 82.166, 3.4],
                      ['1903-12-31', 43.543549635726, 80.632, 3.3],
                      ['1902-12-31', 50.516165104587, 79.163, 3.18],
                      ['1901-12-31', 51.252324438093, 77.584, 3.1],
                      ['1900-12-31', 49.420633813162, 76.094, 3.15],
                      ['1899-12-31', 64.044605796466, 74.799, 3.1],
                      ['1898-12-31', 61.438038202283, 73.494, 3.35],
                      ['1897-12-31', 62.38489275639, 72.189, 3.4],
                      ['1896-12-31', 60.068945428974, 70.885, 3.6],
                      ['1895-12-31', 61.470338429244, 69.58, 3.46],
                      ['1894-12-31', 57.263433799441, 68.275, 3.7],
                      ['1893-12-31', 44.673331550321, 66.97, 3.75],
                      ['1892-12-31', 52.048155015553, 65.666, 3.6],
                      ['1891-12-31', 47.266162908554, 64.361, 3.62],
                      ['1890-12-31', 51.362339834969, 63.056, 3.42]],
             'database_code': 'YALE',
             'database_id': 175,
             'dataset_code': 'RBCI',
             'description': 'Robert J. Shiller, Irrational Exuberance, 2nd. '
                            'Edition, Princeton University Press,2005, 2009, '
                            'Broadway Books 2006, also Subprime Solution, '
                            '2008, as updated by author',
             'end_date': '2018-12-31',
             'frequency': 'annual',
             'id': 32869622,
             'limit': None,
             'name': 'Historical Housing Market Data - Real Building Cost '
                     'Index',
             'newest_available_date': '2018-12-31',
             'oldest_available_date': '1890-12-31',
             'order': None,
             'premium': False,
             'refreshed_at': '2018-10-02T11:30:35.279Z',
             'start_date': '1890-12-31',
             'transform': None,
             'type': 'Time Series'}}

In [17]:
CPI_data = pd.DataFrame(CPI["dataset"]["data"])
CPI_data = CPI_data.rename(columns = {0: "Date", 1:"Cost Index", 2: "U.S. Population (Millions)", 3:"Long Rate"})

In [24]:
CPI_clean = CPI_clean.fillna(0)
CPI_clean = CPI_clean.loc[CPI_clean["Date"] >= "2000-12-31"]

In [25]:
CPI_clean

          Date  Cost Index  U.S. Population (Millions)  Long Rate
0   2018-12-31    0.000000                       0.000       2.83
1   2017-12-31    0.000000                       0.000       2.43
2   2016-12-31    0.000000                     323.242       2.09
3   2015-12-31   88.525400                     321.704       1.88
4   2014-12-31   86.471910                     319.233       2.86
5   2013-12-31   86.059966                     316.796       1.91
6   2012-12-31   85.709698                     314.490       1.97
7   2011-12-31   86.239088                     312.169       3.39
8   2010-12-31   84.613931                     309.807       3.73
9   2009-12-31   84.808355                     307.240       2.52
10  2008-12-31   83.446159                     304.543       3.74
11  2007-12-31   83.196607                     301.696       4.76
12  2006-12-31   82.727011                     298.818       4.42
13  2005-12-31   82.794848                     295.993       4.22
14  2004-12-31   80.773026                     293.262       4.15
15  2003-12-31   76.315435                     290.626       4.05
16  2002-12-31   76.813539                     287.955       5.04
17  2001-12-31   76.640161                     285.225       5.16
18  2000-12-31   78.722001                     282.398       6.66